import type { Match, League, LeagueStanding, LiveTickerItem, StandingEntry, Team } from './types';

// ─── Leagues ───────────────────────────────────────────
export const leagues: League[] = [
  { id: 39, name: 'Premier League', country: 'England', logo: '/leagues/premier-league.svg', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', season: 2025 },
  { id: 140, name: 'La Liga', country: 'Spain', logo: '/leagues/la-liga.svg', flag: '🇪🇸', season: 2025 },
  { id: 135, name: 'Serie A', country: 'Italy', logo: '/leagues/serie-a.svg', flag: '🇮🇹', season: 2025 },
  { id: 78, name: 'Bundesliga', country: 'Germany', logo: '/leagues/bundesliga.svg', flag: '🇩🇪', season: 2025 },
  { id: 61, name: 'Ligue 1', country: 'France', logo: '/leagues/ligue-1.svg', flag: '🇫🇷', season: 2025 },
  { id: 2, name: 'Champions League', country: 'Europe', logo: '/leagues/ucl.svg', flag: '🇪🇺', season: 2025 },
  { id: 3, name: 'Europa League', country: 'Europe', logo: '/leagues/uel.svg', flag: '🇪🇺', season: 2025 },
  { id: 848, name: 'Conference League', country: 'Europe', logo: '/leagues/uecl.svg', flag: '🇪🇺', season: 2025 },
];

// ─── Teams ─────────────────────────────────────────────
const teams: Record<string, Team> = {
  liverpool: { id: 40, name: 'Liverpool', shortName: 'LIV', logo: '/teams/liverpool.svg', code: 'LIV' },
  arsenal: { id: 42, name: 'Arsenal', shortName: 'ARS', logo: '/teams/arsenal.svg', code: 'ARS' },
  mancity: { id: 50, name: 'Manchester City', shortName: 'MCI', logo: '/teams/mancity.svg', code: 'MCI' },
  manunited: { id: 33, name: 'Manchester United', shortName: 'MUN', logo: '/teams/manunited.svg', code: 'MUN' },
  chelsea: { id: 49, name: 'Chelsea', shortName: 'CHE', logo: '/teams/chelsea.svg', code: 'CHE' },
  tottenham: { id: 47, name: 'Tottenham Hotspur', shortName: 'TOT', logo: '/teams/tottenham.svg', code: 'TOT' },
  newcastle: { id: 34, name: 'Newcastle United', shortName: 'NEW', logo: '/teams/newcastle.svg', code: 'NEW' },
  brighton: { id: 51, name: 'Brighton', shortName: 'BHA', logo: '/teams/brighton.svg', code: 'BHA' },
  astonvilla: { id: 66, name: 'Aston Villa', shortName: 'AVL', logo: '/teams/astonvilla.svg', code: 'AVL' },
  westham: { id: 48, name: 'West Ham United', shortName: 'WHU', logo: '/teams/westham.svg', code: 'WHU' },
  realmadrid: { id: 541, name: 'Real Madrid', shortName: 'RMA', logo: '/teams/realmadrid.svg', code: 'RMA' },
  barcelona: { id: 529, name: 'FC Barcelona', shortName: 'BAR', logo: '/teams/barcelona.svg', code: 'BAR' },
  atletico: { id: 530, name: 'Atlético Madrid', shortName: 'ATM', logo: '/teams/atletico.svg', code: 'ATM' },
  bayern: { id: 157, name: 'Bayern Munich', shortName: 'BAY', logo: '/teams/bayern.svg', code: 'BAY' },
  dortmund: { id: 165, name: 'Borussia Dortmund', shortName: 'BVB', logo: '/teams/dortmund.svg', code: 'BVB' },
  psg: { id: 85, name: 'Paris Saint-Germain', shortName: 'PSG', logo: '/teams/psg.svg', code: 'PSG' },
  juventus: { id: 496, name: 'Juventus', shortName: 'JUV', logo: '/teams/juventus.svg', code: 'JUV' },
  acmilan: { id: 489, name: 'AC Milan', shortName: 'MIL', logo: '/teams/acmilan.svg', code: 'MIL' },
  inter: { id: 505, name: 'Inter Milan', shortName: 'INT', logo: '/teams/inter.svg', code: 'INT' },
  napoli: { id: 492, name: 'Napoli', shortName: 'NAP', logo: '/teams/napoli.svg', code: 'NAP' },
};

// ─── Mock Matches ──────────────────────────────────────
const today = new Date().toISOString().split('T')[0];

export const mockMatches: Match[] = [
  // LIVE matches
  {
    id: 1001,
    league: leagues[0],
    homeTeam: teams.liverpool,
    awayTeam: teams.arsenal,
    score: { home: 2, away: 1, htHome: 1, htAway: 0 },
    status: '2H',
    minute: 67,
    date: today,
    time: '15:00',
    venue: 'Anfield',
    referee: 'Michael Oliver',
    events: [
      { id: 'e1', type: 'goal', minute: 12, team: 'home', player: 'Mohamed Salah', assist: 'Trent Alexander-Arnold' },
      { id: 'e2', type: 'yellow_card', minute: 28, team: 'away', player: 'Declan Rice' },
      { id: 'e3', type: 'goal', minute: 53, team: 'away', player: 'Bukayo Saka', assist: 'Martin Ødegaard' },
      { id: 'e4', type: 'goal', minute: 61, team: 'home', player: 'Darwin Núñez' },
      { id: 'e5', type: 'substitution', minute: 65, team: 'home', player: 'Cody Gakpo', detail: 'Luis Díaz off' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '58%', away: '42%' },
      { type: 'Total Shots', home: 14, away: 9 },
      { type: 'Shots on Target', home: 6, away: 3 },
      { type: 'Corner Kicks', home: 7, away: 4 },
      { type: 'Fouls', home: 8, away: 12 },
      { type: 'Offsides', home: 2, away: 1 },
      { type: 'Yellow Cards', home: 0, away: 1 },
      { type: 'Passes Accurate', home: '412 (87%)', away: '298 (81%)' },
      { type: 'Expected Goals (xG)', home: '1.82', away: '0.94' },
    ],
    lineups: {
      home: {
        formation: '4-3-3',
        startXI: [
          { id: 1, name: 'Alisson', number: 1, position: 'GK' },
          { id: 2, name: 'Alexander-Arnold', number: 66, position: 'RB' },
          { id: 3, name: 'Van Dijk', number: 4, position: 'CB' },
          { id: 4, name: 'Konaté', number: 5, position: 'CB' },
          { id: 5, name: 'Robertson', number: 26, position: 'LB' },
          { id: 6, name: 'Mac Allister', number: 10, position: 'CM' },
          { id: 7, name: 'Szoboszlai', number: 8, position: 'CM' },
          { id: 8, name: 'Gravenberch', number: 38, position: 'CM' },
          { id: 9, name: 'Salah', number: 11, position: 'RW' },
          { id: 10, name: 'Núñez', number: 9, position: 'ST' },
          { id: 11, name: 'Díaz', number: 7, position: 'LW' },
        ],
        substitutes: [
          { id: 12, name: 'Kelleher', number: 62, position: 'GK' },
          { id: 13, name: 'Gakpo', number: 18, position: 'FW' },
          { id: 14, name: 'Jones', number: 17, position: 'MF' },
          { id: 15, name: 'Elliott', number: 19, position: 'MF' },
          { id: 16, name: 'Tsimikas', number: 21, position: 'DF' },
        ],
        coach: 'Arne Slot',
      },
      away: {
        formation: '4-3-3',
        startXI: [
          { id: 20, name: 'Raya', number: 22, position: 'GK' },
          { id: 21, name: 'White', number: 4, position: 'RB' },
          { id: 22, name: 'Saliba', number: 2, position: 'CB' },
          { id: 23, name: 'Gabriel', number: 6, position: 'CB' },
          { id: 24, name: 'Timber', number: 12, position: 'LB' },
          { id: 25, name: 'Ødegaard', number: 8, position: 'CM' },
          { id: 26, name: 'Rice', number: 41, position: 'CM' },
          { id: 27, name: 'Havertz', number: 29, position: 'CM' },
          { id: 28, name: 'Saka', number: 7, position: 'RW' },
          { id: 29, name: 'Havertz', number: 29, position: 'ST' },
          { id: 30, name: 'Martinelli', number: 11, position: 'LW' },
        ],
        substitutes: [
          { id: 31, name: 'Ramsdale', number: 1, position: 'GK' },
          { id: 32, name: 'Trossard', number: 19, position: 'FW' },
          { id: 33, name: 'Jorginho', number: 20, position: 'MF' },
          { id: 34, name: 'Zinchenko', number: 35, position: 'DF' },
          { id: 35, name: 'Nketiah', number: 14, position: 'FW' },
        ],
        coach: 'Mikel Arteta',
      },
    },
  },
  {
    id: 1002,
    league: leagues[0],
    homeTeam: teams.mancity,
    awayTeam: teams.chelsea,
    score: { home: 0, away: 0 },
    status: '1H',
    minute: 23,
    date: today,
    time: '15:00',
    venue: 'Etihad Stadium',
    referee: 'Anthony Taylor',
    events: [
      { id: 'e10', type: 'yellow_card', minute: 18, team: 'home', player: 'Rodri' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '64%', away: '36%' },
      { type: 'Total Shots', home: 5, away: 2 },
      { type: 'Shots on Target', home: 1, away: 0 },
      { type: 'Corner Kicks', home: 3, away: 1 },
      { type: 'Fouls', home: 4, away: 6 },
    ],
    lineups: undefined,
  },
  {
    id: 1003,
    league: leagues[1],
    homeTeam: teams.realmadrid,
    awayTeam: teams.barcelona,
    score: { home: 1, away: 1, htHome: 1, htAway: 1 },
    status: 'HT',
    minute: 45,
    date: today,
    time: '20:00',
    venue: 'Santiago Bernabéu',
    referee: 'Jesús Gil Manzano',
    events: [
      { id: 'e20', type: 'goal', minute: 15, team: 'home', player: 'Vinícius Jr.', assist: 'Jude Bellingham' },
      { id: 'e21', type: 'goal', minute: 34, team: 'away', player: 'Robert Lewandowski', assist: 'Pedri' },
      { id: 'e22', type: 'yellow_card', minute: 40, team: 'home', player: 'Aurélien Tchouaméni' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '45%', away: '55%' },
      { type: 'Total Shots', home: 8, away: 10 },
      { type: 'Shots on Target', home: 3, away: 4 },
      { type: 'Corner Kicks', home: 3, away: 5 },
      { type: 'Fouls', home: 9, away: 7 },
      { type: 'Expected Goals (xG)', home: '0.78', away: '1.12' },
    ],
    lineups: undefined,
  },
  // Half Time match
  {
    id: 1004,
    league: leagues[2],
    homeTeam: teams.inter,
    awayTeam: teams.acmilan,
    score: { home: 2, away: 0, htHome: 2, htAway: 0 },
    status: 'HT',
    minute: 45,
    date: today,
    time: '20:45',
    venue: 'San Siro',
    referee: 'Daniele Orsato',
    events: [
      { id: 'e30', type: 'goal', minute: 11, team: 'home', player: 'Lautaro Martínez' },
      { id: 'e31', type: 'goal', minute: 38, team: 'home', player: 'Marcus Thuram', assist: 'Nicolò Barella' },
      { id: 'e32', type: 'yellow_card', minute: 25, team: 'away', player: 'Theo Hernández' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '52%', away: '48%' },
      { type: 'Total Shots', home: 11, away: 4 },
      { type: 'Shots on Target', home: 5, away: 1 },
    ],
    lineups: undefined,
  },
  // Upcoming matches
  {
    id: 2001,
    league: leagues[0],
    homeTeam: teams.tottenham,
    awayTeam: teams.newcastle,
    score: { home: 0, away: 0 },
    status: 'NS',
    date: today,
    time: '17:30',
    venue: 'Tottenham Hotspur Stadium',
    events: [],
  },
  {
    id: 2002,
    league: leagues[3],
    homeTeam: teams.bayern,
    awayTeam: teams.dortmund,
    score: { home: 0, away: 0 },
    status: 'NS',
    date: today,
    time: '18:30',
    venue: 'Allianz Arena',
    events: [],
  },
  {
    id: 2003,
    league: leagues[4],
    homeTeam: teams.psg,
    awayTeam: teams.napoli,
    score: { home: 0, away: 0 },
    status: 'NS',
    date: today,
    time: '21:00',
    venue: 'Parc des Princes',
    events: [],
  },
  {
    id: 2004,
    league: leagues[5],
    homeTeam: teams.barcelona,
    awayTeam: teams.bayern,
    score: { home: 0, away: 0 },
    status: 'NS',
    date: today,
    time: '21:00',
    venue: 'Spotify Camp Nou',
    events: [],
  },
  // Finished matches
  {
    id: 3001,
    league: leagues[0],
    homeTeam: teams.brighton,
    awayTeam: teams.astonvilla,
    score: { home: 1, away: 2, htHome: 0, htAway: 1, ftHome: 1, ftAway: 2 },
    status: 'FT',
    date: today,
    time: '12:30',
    venue: 'Amex Stadium',
    events: [
      { id: 'e40', type: 'goal', minute: 22, team: 'away', player: 'Ollie Watkins' },
      { id: 'e41', type: 'goal', minute: 56, team: 'home', player: 'Kaoru Mitoma' },
      { id: 'e42', type: 'red_card', minute: 72, team: 'home', player: 'Lewis Dunk' },
      { id: 'e43', type: 'goal', minute: 81, team: 'away', player: 'Leon Bailey', assist: 'Ollie Watkins' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '55%', away: '45%' },
      { type: 'Total Shots', home: 12, away: 15 },
      { type: 'Shots on Target', home: 4, away: 6 },
      { type: 'Corner Kicks', home: 6, away: 5 },
      { type: 'Fouls', home: 11, away: 9 },
      { type: 'Expected Goals (xG)', home: '1.22', away: '1.87' },
    ],
    lineups: undefined,
  },
  {
    id: 3002,
    league: leagues[1],
    homeTeam: teams.atletico,
    awayTeam: teams.realmadrid,
    score: { home: 0, away: 3, htHome: 0, htAway: 1, ftHome: 0, ftAway: 3 },
    status: 'FT',
    date: today,
    time: '14:00',
    venue: 'Cívitas Metropolitano',
    events: [
      { id: 'e50', type: 'goal', minute: 31, team: 'away', player: 'Jude Bellingham' },
      { id: 'e51', type: 'yellow_card', minute: 45, team: 'home', player: 'Stefan Savić' },
      { id: 'e52', type: 'goal', minute: 55, team: 'away', player: 'Vinícius Jr.', assist: 'Luka Modrić' },
      { id: 'e53', type: 'goal', minute: 78, team: 'away', player: 'Rodrygo' },
    ],
    statistics: [
      { type: 'Ball Possession', home: '38%', away: '62%' },
      { type: 'Total Shots', home: 7, away: 18 },
      { type: 'Shots on Target', home: 2, away: 8 },
    ],
    lineups: undefined,
  },
  {
    id: 3003,
    league: leagues[0],
    homeTeam: teams.manunited,
    awayTeam: teams.westham,
    score: { home: 3, away: 1, htHome: 2, htAway: 0, ftHome: 3, ftAway: 1 },
    status: 'FT',
    date: today,
    time: '12:30',
    venue: 'Old Trafford',
    events: [
      { id: 'e60', type: 'goal', minute: 8, team: 'home', player: 'Bruno Fernandes' },
      { id: 'e61', type: 'goal', minute: 33, team: 'home', player: 'Rasmus Højlund', assist: 'Bruno Fernandes' },
      { id: 'e62', type: 'goal', minute: 52, team: 'away', player: 'Jarrod Bowen' },
      { id: 'e63', type: 'yellow_card', minute: 67, team: 'away', player: 'Tomáš Souček' },
      { id: 'e64', type: 'goal', minute: 74, team: 'home', player: 'Marcus Rashford' },
    ],
    statistics: [],
    lineups: undefined,
  },
];

// ─── Mock Standings ────────────────────────────────────
function createStandingEntry(rank: number, team: Team, w: number, d: number, l: number, gf: number, ga: number, form: string, desc?: string): StandingEntry {
  return {
    rank,
    team,
    played: w + d + l,
    won: w,
    drawn: d,
    lost: l,
    goalsFor: gf,
    goalsAgainst: ga,
    goalDifference: gf - ga,
    points: w * 3 + d,
    form,
    description: desc,
  };
}

export const mockStandings: LeagueStanding[] = [
  {
    league: leagues[0],
    standings: [
      createStandingEntry(1, teams.liverpool, 20, 5, 1, 58, 18, 'WWWDW', 'Champions League'),
      createStandingEntry(2, teams.arsenal, 19, 5, 2, 52, 20, 'WDWWW', 'Champions League'),
      createStandingEntry(3, teams.mancity, 18, 4, 4, 55, 25, 'WLWWD', 'Champions League'),
      createStandingEntry(4, teams.astonvilla, 16, 5, 5, 48, 30, 'DWWLW', 'Champions League'),
      createStandingEntry(5, teams.tottenham, 15, 4, 7, 52, 38, 'WLWDL', 'Europa League'),
      createStandingEntry(6, teams.newcastle, 14, 6, 6, 45, 28, 'WDDWL', 'Europa League'),
      createStandingEntry(7, teams.chelsea, 14, 5, 7, 48, 35, 'LWWDW', 'Conference League'),
      createStandingEntry(8, teams.brighton, 13, 6, 7, 45, 38, 'DLWWL'),
      createStandingEntry(9, teams.manunited, 12, 4, 10, 35, 38, 'WLLWW'),
      createStandingEntry(10, teams.westham, 10, 5, 11, 33, 42, 'LLDWL'),
    ],
  },
  {
    league: leagues[1],
    standings: [
      createStandingEntry(1, teams.realmadrid, 21, 4, 1, 60, 18, 'WWWWW', 'Champions League'),
      createStandingEntry(2, teams.barcelona, 19, 5, 2, 58, 22, 'DWWWW', 'Champions League'),
      createStandingEntry(3, teams.atletico, 16, 6, 4, 42, 22, 'WDWDL', 'Champions League'),
    ],
  },
  {
    league: leagues[2],
    standings: [
      createStandingEntry(1, teams.inter, 22, 3, 1, 62, 16, 'WWWWW', 'Champions League'),
      createStandingEntry(2, teams.napoli, 18, 5, 3, 50, 22, 'WDWWL', 'Champions League'),
      createStandingEntry(3, teams.juventus, 16, 7, 3, 44, 20, 'DDWWW', 'Champions League'),
      createStandingEntry(4, teams.acmilan, 15, 5, 6, 45, 30, 'WLWDW', 'Champions League'),
    ],
  },
  {
    league: leagues[3],
    standings: [
      createStandingEntry(1, teams.bayern, 20, 3, 3, 68, 22, 'WWDWW', 'Champions League'),
      createStandingEntry(2, teams.dortmund, 17, 5, 4, 55, 30, 'WDWLW', 'Champions League'),
    ],
  },
];

// ─── Mock Live Ticker ──────────────────────────────────
export const mockTickerItems: LiveTickerItem[] = [
  {
    id: 't1',
    matchId: 1001,
    type: 'goal',
    message: '⚽ GOAL! Darwin Núñez scores for Liverpool! Liverpool 2-1 Arsenal (61\')',
    minute: 61,
    timestamp: new Date().toISOString(),
  },
  {
    id: 't2',
    matchId: 1003,
    type: 'goal',
    message: '⚽ GOAL! Robert Lewandowski equalizes! Real Madrid 1-1 Barcelona (34\')',
    minute: 34,
    timestamp: new Date().toISOString(),
  },
  {
    id: 't3',
    matchId: 1004,
    type: 'goal',
    message: '⚽ GOAL! Marcus Thuram doubles the lead! Inter 2-0 AC Milan (38\')',
    minute: 38,
    timestamp: new Date().toISOString(),
  },
  {
    id: 't4',
    matchId: 1002,
    type: 'yellow_card',
    message: '🟨 Yellow Card: Rodri (Manchester City) vs Chelsea (18\')',
    minute: 18,
    timestamp: new Date().toISOString(),
  },
  {
    id: 't5',
    matchId: 3001,
    type: 'red_card',
    message: '🟥 Red Card! Lewis Dunk (Brighton) sent off vs Aston Villa (72\')',
    minute: 72,
    timestamp: new Date().toISOString(),
  },
];